name: Epic
favicon: null
layout_spectrum: 0.31515
typography_spectrum: 0.20805
title: Epic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-78063794-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090900'
    - '#97c1cf'
    - '#5b96b6'
    - '#574d44'
    - '#00364e'
  brandStrength: 0.1875
  lightness: 0.05415430152788758
  saturation: 0.75
  rhythmicContrast: 0.8108918305952102
purpose: []
