name: Epic
favicon: null
layout_spectrum: 0.31515
typography_spectrum: 0.20805
title: Epic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-78063794-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.42234877939336
  lightness: 0.05415430152788758
  saturation: 0.5027704620733857
  rhythmicContrast: 0.8108918305952102
purpose: []
